---

- name: packages-pip | Install pipx and pipx packages
  block:
    - name: Wait for locks
      ansible.builtin.include_tasks:
        file: wait_for_locks.yml

    - name: packages-pip | Install pipx
      ansible.builtin.package:
        name: pipx
        state: present
      environment:
        PIPX_HOME: /usr/local/share/pipx
        PIPX_BIN_DIR: /usr/local/bin
      register: pipx_install
      until: pipx_install is not failed


    - name: packages-pip | Install python requirements via Pip (All Distributions)
      community.general.pipx:
        name: "{{ item }}"
        state: present
      loop: "{{ common_pip_pkgs | default([]) }}"
      when:
        - (common_pip_pkgs | length) > 0 | default([])
      register: pip_package_install
      until: pip_package_install is not failed
      environment:
        PIPX_HOME: /usr/local/share/pipx
        PIPX_BIN_DIR: /usr/local/bin
