---

- name: Create local user groups
  ansible.builtin.group:
    name: "{{ item.key }}"
    gid: "{{ item.value.gid | default(omit) }}"
    state: present
  loop: "{{ ssh_groups | dict2items }}"
  loop_control:
    label: "group: {{ item.key }}"
  when:
    - ssh_groups is defined
    - ssh_groups != None
- name: Create local user accounts
  ansible.builtin.user:
    name: "{{ item.key }}"
    shell: "{{ item.value.shell | default(omit) }}"
    group: "{{ item.value.gid | default(omit) }}"
    groups: |
      {% set grouplist = [] %}
      {% for group in ssh_groups | dict2items %}
      {% if item.key in group.value.members %}
      {{ grouplist.append(group.key) }}
      {% endif %}
      {% endfor %}
      {{ grouplist|join(',') }}
    uid: "{{ item.value.uid | default(omit) }}"
    password: "{{ item.value.password | password_hash('sha512', vault_root_password_salt) | default(omit) }}"
  loop: "{{ ssh_users | dict2items }}"
  loop_control:
    label: "user: {{ item.key }}"
  when:
    - ssh_users is defined
    - ssh_users != None

- name: Add user authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{ item.value.pubkey }}"
  loop: "{{ ssh_users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - ssh_users is defined
    - ssh_users != None
    - item.value.pubkey is defined
