---
- name: Restart SSHD
  ansible.builtin.service:
    name: "{{ common_sshd_service }}"
    state: restarted
    enabled: true
  register: ssh_started

- name: Update Grub
  ansible.builtin.command:
    cmd: "{{ common_grub_update_cmd }} -o {{ common_grub_config }}"
  register: grub_update_result
  changed_when:
    - grub_update_result is success
  notify:
    - Reboot System

- name: Update Initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u -k all
  register: initramfs_update_result
  changed_when:
    - initramfs_update_result is success
  notify:
    - Reboot System

- name: Reboot System
  ansible.builtin.reboot:
    post_reboot_delay: 30
    reboot_timeout: 600
    msg: Reboot initiated by Ansible
  register: reboot_result
  changed_when: reboot_result is success
  notify: Wait For System

- name: Wait For System
  ansible.builtin.wait_for_connection:
    timeout: 600

- name: Assert
  ansible.builtin.assert:
    fail_msg: |
      Failed: {{ assert.msg }}
      Debug: {{ assert }}
    quiet: false
    success_msg: |
      Success: {{ assert.msg }}
      Debug: {{ assert }}
    that:
      - assert is not failed
